### PR TITLE
Adding unit tests

### PR DESCRIPTION
**Pull request by jpfairbanks**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
This PR does the following:

1. add Petri -> ODEProblem conversion
2. refactor Petri.jl into multiple files
    - types.jl, the type definitions
    - stochastic.jl the conversion of Model -> stochastic simulation
    - ode.jl, the conversion of Model -> ODEProblem
    - metaprogramming, tools for working with Expr trees
3. add example
4. add tests
5. add CT tests that aren't included because of dependencies

An open question is what to do about testing the interaction between SemanticModels.jl and Petri.jl. I'm inclined to put all the code for the integration into SemanticModels.jl in a submodule. Pkg.jl will support multiple packages in one repository, which will make this easier.

**Comment by mehalter** [comment]
It looks good other than it breaking the testing, could you fix the errors with travis? I believe its just missing some packages ("LabelledArrays") at least. Once we get it passing testing I think it can go to master.

**Comment by jpfairbanks** [comment]
Yeah, how do I do "test time" dependencies again?

**Comment by jpfairbanks** [comment]
I copied it from SemanticModels.

**Comment by jpfairbanks** [comment]
I think this is ready to go. Probably a good idea to *squash and merge*

**Review by mehalter — APPROVED** [review]
LGTM

**Pull request merged**
